routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\SEOKeywordController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\WebsiteController;
use App\Http\Controllers\GeneratorController;
use App\Http\Controllers\BlogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes();
// login routes


Route::get('', [App\Http\Controllers\WebsiteController::class, 'index'])->name('website');
Route::get('about-us', [App\Http\Controllers\WebsiteController::class, 'aboutUs'])->name('about_us');
Route::get('blog-post', [App\Http\Controllers\WebsiteController::class, 'blogs'])->name('blogs');
Route::get('blog-post/{slug}', [App\Http\Controllers\WebsiteController::class, 'blogsDetails'])->name('blogs_details');
Route::get('generator', [App\Http\Controllers\WebsiteController::class, 'generator'])->name('generator');
Route::get('privacy-policy', [App\Http\Controllers\WebsiteController::class, 'privacy'])->name('privacy');
Route::get('terms-and-condition', [App\Http\Controllers\WebsiteController::class, 'terms'])->name('terms');
Route::get('/ads.txt', function () {
    $content = view('ads');
    return response($content, 200)
        ->header('content-Type', 'text');
});

Route::post('generate', [GeneratorController::class, 'generate'])->name('generate');

// dashboard
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');

Route::group(['prefix' => 'password', 'as' => 'password.'], function(){
	Route::controller(ForgotPasswordController::class)->group(function () {
		Route::get('reset', 'showLinkRequestForm')->name('request');
		Route::post('email', 'sendResetLinkEmail')->name('email');
		Route::get('reset/{token}', 'showResetForm')->name('reset');
		Route::post('reset', 'reset')->name('update');
	});
});

Route::group(['prefix' => 'ckeditor', 'as' => 'ckeditor.'], function(){
	Route::controller(WebsiteController::class)->group(function () {
		Route::post('/upload', 'upload')->name('upload');
	});
});


Route::group(['prefix' => 'blogs', 'as' => 'blogs.'], function(){
	Route::controller(BlogController::class)->group(function () {
		Route::get('', 'index')->name('index');
		Route::get('list', 'list')->name('list');
		Route::get('add', 'add')->name('add');
		Route::get('edit/{id?}', 'edit')->name('edit');
		Route::post('save/{id?}', 'save')->name('save');
		Route::get('find/{id?}', 'find')->name('find');
		Route::delete('delete/{id?}', 'delete')->name('delete');
	});
});

Route::group(['prefix' => 'test', 'as' => 'test.'], function(){
	Route::controller(SEOKeywordController::class)->group(function () {
		Route::get('link', 'extractProductDetails')->name('test');
	});
});


Route::group(['middleware' => 'role:admin'], function () {
		
});

Route::group(['middleware' => 'role:user'], function () {
    // User routes/controllers here
});

app/Models/Blog.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
	use HasFactory;

	protected $fillable = [
		'blog_title',
		'contents',
		'meta_description',
		'meta_keyword',
	];
}

app/Http/Controllers/BlogController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Blog;
use Validator;
use File;
use Str;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
	public function index(){
		return view('Blog.index');
	}

	public function list(){
		$blogs = Blog::get();
		return response()->json(['status' => true, 'data' => $blogs ]);
	}


	function makeCKContent($filename, $ck_contents){
	    Storage::disk('ck')->put($filename, $ck_contents);
	    return $filename;

	}

	public function save(Request $request, $id = ""){
			$is__require = (empty($id))? 'required|file|max:10240|mimes:jpeg,png,JPEG,jpg,GIF,gif,web' : '';

		$validator = Validator::make($request->all(), [
			'blog_thumbnail' => $is__require,
			'blog_title' => 'required',
			'contents' => 'required',
			'meta_description' => 'required',
			'meta_keyword' => 'required',
		]);

		if($validator->fails()){
			return response()->json(['status' => false, 'error' => $validator->errors() ]);
		}else{
			

			if(!empty($id)){
				$blogs = Blog::find($id);

				$filename = $blogs->contents ?? 'blogs_'.Str::random(8).'.txt'; 
                $ck = $this->makeCKContent($filename, $request->contents);

				$blogs->blog_title = $request->get('blog_title');
				$blogs->contents = $ck;
				$blogs->meta_description = $request->get('meta_description');
				$blogs->meta_keywords = $request->get('meta_keyword');
				
				if ($request->hasFile('blog_thumbnail') && $request->file('blog_thumbnail')->isValid()) {
			        $blogs->blog_thumbnail = 'storage/'.$request->file('blog_thumbnail')->store('blog_thumbnail', 'public');
			    }

				if($blogs->save()){
					return response()->json(['status' => true, 'message' => 'blogs saved successfully!']);
				}
			}else{
				$filename = 'blogs_'.Str::random(8).'.txt'; 
                $ck = $this->makeCKContent($filename, $request->contents);

				$blogs = new Blog();
				$blogs->blog_title = $request->get('blog_title');
				$blogs->contents = $ck;
				$blogs->meta_description = $request->get('meta_description');
				$blogs->meta_keywords = $request->get('meta_keyword');
				
				if ($request->hasFile('blog_thumbnail') && $request->file('blog_thumbnail')->isValid()) {
			        $blogs->blog_thumbnail = 'storage/'.$request->file('blog_thumbnail')->store('blog_thumbnail', 'public');
			    }

				if($blogs->save()){
					return response()->json(['status' => true, 'message' => 'blogs saved successfully!']);
				}
			}
		}
	}

	public function edit($id){
		$title = 'Edit Blogs';
		$blogs = Blog::findOrFail($id);
		return view('Blog.add', compact('blogs', 'title'));
	}

	public function add(){
		$title = 'Add Blogs';
		return view('Blog.add', compact('title'));
	}

	public function find($id){
		$blogs = Blog::findOrFail($id);
		return response()->json(['status' => true, 'data' => $blogs ]);
	}

	public function delete($id){
		$blogs = Blog::findOrFail($id);
		if($blogs->delete()){
			return response()->json(['status' => true, 'message' => 'Record deleted successfully!' ]);
		}
	}

}

resources/views/Blog/add.blade.php
@extends('layouts.app')

@section('title', 'Create Products')

@section('breadcrumbs')
@include('layouts.bread', ['paths' => ['Blogs' => route('blogs.index'), 'Create Blog Post' => '']])
@endsection

@section('content')
<div class="border-bottom mb-5 pb-3 row">
  <div class="col-lg-4 h1">Create Blog</div>
</div>

<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form class="needs-validation" method="post" id="blog_form" action="{{ route('blogs.save') }}/{{ $blogs->id ?? '' }}" novalidate>
                        @csrf
                        <div class="row">
                           <input type="hidden" name="id" id="id" value="{{ $blogs->id ?? '' }}"/>
                           <div class="col-12 mb-3">
                                 @if(!empty($blogs->blog_thumbnail))
                                 <img src="{{ asset($blogs->blog_thumbnail) }}" class="img-thumbnail rounded mt-3" id="blog_thumbnail_preview" onclick="$('#blog_thumbnail').click();" style="cursor: pointer;">
                                @else
                                 <img src="{{ asset('img/thumb2.jpg') }}" class="img-thumbnail rounded mt-3" id="blog_thumbnail_preview" onclick="$('#blog_thumbnail').click();" style="cursor: pointer;">
                                @endif
                                 <input type="file" name="blog_thumbnail" id="blog_thumbnail" class="form-control preview-upload mt-2" data-preview-selector="blog_thumbnail_preview">
                                
                            </div>
                            <div class="my-3">
                                <hr>
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="mb-2">Blog title</label>
                                <input type="text" name="blog_title" id="blog_title" class="form-control " required value="{{ $blogs->blog_title ?? '' }}" placeholder="Enter blog title"/>
                            </div>
                             @php
                                $html_content = (!empty($blogs->contents))? file_get_contents(asset('storage/ck_html/'.$blogs->contents)) : '';
                            @endphp
                            <div class="col-md-12 mb-3">
                                <label class="mb-2">Contents</label>
                                <textarea id="contents_html" name="contents_html" class="d-none">{!! $html_content !!}</textarea>
                                <input type="hidden" id="contents" name="contents" class="form-control">
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="mb-2">Meta description</label>
                                <textarea type="textarea" name="meta_description" id="meta_description" class="form-control " required placeholder="Enter meta description">{{ $blogs->meta_description ?? '' }}</textarea>
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="mb-2">Meta keyword</label>
                                <textarea type="textarea" name="meta_keyword" id="meta_keyword" class="form-control " required placeholder="Enter meta keyword">{{ $blogs->meta_keywords ?? '' }}</textarea>
                            </div>
                            <div class="col-md-12 text-end">
                                <button type="submit" class="btn btn-success" id="blog_form_btn" >Save</button>
                            </div> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
<script src="{{ asset('plugins/ckeditor/ckeditor.js') }}"></script>

<script type="text/javascript">
 $(document).ready(function(){
    CKEDITOR.replace('contents_html', {
      extraPlugins: 'uploadimage',
        filebrowserUploadUrl : "{{ route('ckeditor.upload', ['_token' => CSRF_TOKEN()]) }}",
      height: 1000,
    }).config.allowedContent = true;
  });

$("#blog_form").on('submit', function(e){
    e.preventDefault();
    $('#contents').val(CKEDITOR.instances['contents_html'].getData());
    let form = $(this)[0]; // Use $(this) instead of $("#product_form")
    let data = new FormData(form);
    let url = $(this).attr('action');

    $.ajax({
      type:"POST",
      url:url,
      data:data,
      enctype: 'multipart/form-data',
      processData: false,  // Important!
      contentType: false,
      dataType:'json',
        beforeSend:function(){
            $('#blog_form').prop('disabled', true);
        },
        success:function(response){
            // console.log(response);
            if (response.status == true) {
                swal("Success", response.message, "success");
                setTimeout(function(){
                    window.location = "{{ route('blogs.index') }}";
                }, 1500);
            }else{
                console.log(response);
            }
                validation('blogs_form', response.error);
                $('#blog_form').prop('disabled', false);
        },
        error: function(error){
            $('#blog_form').prop('disabled', false);
            console.log(error);
        }
    });
});

</script>
</script>
@endpush

resources/views/Blog/index.blade.php
@extends('layouts.app')

@section('title', 'Shops')


@section('breadcrumbs')
@include('layouts.bread', ['paths' => ['Blogs' => '']])
@endsection

@section('content')
<div class="border-bottom mb-5 pb-3 row">
  <div class="col-lg-4 h1">Blogs Management</div>
  <div class="col-lg-8 text-end">
     <a href="{{ route('blogs.add') }}" class="btn btn-primary">Add Blog Post</a>
  </div>
</div>

<div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered table-striped" id="tbl_blogs" style="width: 100%;"></table>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('js')
<script type="text/javascript">
  var tbl_blogs;
show_blogs();
function show_blogs(){
    if(tbl_blogs){
        tbl_blogs.destroy();
    }
    tbl_samples = $('#tbl_blogs').DataTable({
        destroy: true,
        pageLength: 10,
        responsive: true,
        ajax: "{{ route('blogs.list') }}",
        deferRender: true,
        columns: [
            {
                className: '',
                "data": 'blog_title',
                "title": 'Blog title',
            },
            {
                className: '',
                "data": 'contents',
                "title": 'Contents',
            },
            {
                className: '',
                "data": 'meta_description',
                "title": 'Meta description',
            },
            {
                className: '',
                "data": 'meta_keywords',
                "title": 'Meta keyword',
            },
            {
                className: 'width-option-1 text-center',
                width: '15%',
                "data": 'id',
                "orderable": false,
                "title": 'Options',
                "render": function(data, type, row, meta){
                    newdata = '';
                    newdata += '<a href="{{ route('blogs.edit') }}/'+row.id+'" class="btn btn-success btn-sm font-base mt-1" ><i class="fa fa-edit"></i></a> ';
                    newdata += ' <button class="btn btn-danger btn-sm font-base mt-1" onclick="delete_blogs('+row.id+');" type="button"><i class="fa fa-trash"></i></button>';
                    return newdata;
                }
            }
        ]
    });
}


function delete_blogs(id){
    swal({
        title: "Are you sure?",
        text: "Do you want to delete blogs?",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "Yes",
        closeOnConfirm: false
    },
    function(){
        $.ajax({
            type:"DELETE",
            url:"{{ route('blogs.delete') }}/"+id,
            data:{},
            dataType:'json',
            beforeSend:function(){
        },
        success:function(response){
            // console.log(response);
            if (response.status == true) {
                show_blogs();
                swal("Success", response.message, "success");
            }else{
                console.log(response);
            }
        },
        error: function(error){
            console.log(error);
        }
        });
    });
}

</script>
@endpush